# _config.yml

# Site settings
# These are used to personalize your new site.
title: "CA. Anup Acharya - Data Science Portfolio" # Full title for browser, SEO
author_name: "CA. Anup Acharya" # Shorter name for display in header/footer
email: "longlivenepal48@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Anup Acharya's professional data science portfolio, showcasing CV, 
  data analysis projects, big data expertise, and Kaggle competition entries.

# URL and BaseURL settings - CRITICAL for GitHub Pages
# Your site is hosted at: https://longlivenepal48.github.io/portfolio/
url: "https://longlivenepal48.github.io" # This is the root domain for your GitHub Pages. DO NOT include /portfolio here.
baseurl: "/portfolio" # This is the subpath for your specific repository. MUST start with a forward slash.

# GitHub specific (optional, but can be used by themes or plugins)
github_username: "longlivenepal48"
# github_repo: "portfolio" # This can be inferred, not strictly needed if baseurl is correct

# Social links (used in _layouts/default.html)
linkedin_username: "ca-anup-acharya-761737ba" # Just the username part from the LinkedIn URL

# Build settings
markdown: kramdown
theme: null # We are using custom styling

# Plugins - Ensure these are correctly listed and also in your Gemfile
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md 
  - LICENSE.md # If you have a LICENSE.md 
  - "*.Rmd" # Uncomment if Rmd files are ONLY for generating HTML separately and NOT Jekyll pages