# _config.yml

# Your existing title, email, description, baseurl, url, etc. should remain here
title: CA. Anup Acharya - Data Science Portfolio
email: longlivenepal48@gmail.com
description: >-
  Anup Acharya's professional data science portfolio, showcasing CV, 
  data analysis projects, big data expertise, and Kaggle competition entries.
baseurl: "/anup_portfolio" # Crucial: Ensure this matches your GitHub Pages subpath
url: "https://longlivenepal48.github.io" # Crucial: Your GitHub Pages domain

github_username: longlivenepal48
# github_repo: anup_portfolio # Optional, can be derived
linkedin_username: ca-anup-acharya-761737ba

# Build settings
markdown: kramdown # Ensure kramdown is specified if you added it to Gemfile
theme: null       # Since you have custom styling

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag # This line is key

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/      # Bundler's typical install path if specified
  # - README.md  # Uncomment if you don't want README.md built into an HTML page
  # - LICENSE    # Uncomment if you don't want LICENSE built into an HTML page